In [ ]:
# Importing NumPy library as 'np' for numerical operations
import numpy as np

In [2]:
# Creating a 1D NumPy array with 3 elements
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
# Creating a 2D NumPy array (2 rows, 3 columns)
arr2 = np.array([[1,2,3], [2,3,5]])
print(arr2)

[[1 2 3]
 [2 3 5]]


In [5]:
# Creating another 2D NumPy square matrix (3x3)
arr3 = np.array([[1,5,9], [9,8,7], [1,5,2]])
arr3

array([[1, 5, 9],
       [9, 8, 7],
       [1, 5, 2]])

In [7]:
# Creating a 2x3 NumPy array filled with zeros
#zero array
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Creating a 2x3 NumPy array filled with ones
ones_arr = np.ones((2,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Creating a NumPy array with values from 1 to 19, step 3
arrage_arr = np.arange(1,20,3)
print(arrage_arr)

[ 1  4  7 10 13 16 19]


In [18]:
# Creating 5 equally spaced numbers from 1 to 20
linspace_arr = np.linspace(1,20,5)
print(linspace_arr)

[ 1.    5.75 10.5  15.25 20.  ]


In [19]:
#creating a array
#creating a array having zeros
#creating a array having ones
#creating a array start with 1, end with 20 having increase of 2
#creating a array start with 10, end with 20 having 5 digits divided equally

In [22]:
# Creating and printing a simple 1D NumPy array
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [25]:
# Task 1: 1D array with values from 5 to 25 using linspace
#Task 1 : Create a 1D NumPy array containing values from 5 to 25 with a step of 5.
array1 = np.linspace(5,25,5)
print(array1)

[ 5. 10. 15. 20. 25.]


In [29]:
# Creating a 2x3 NumPy array filled with ones
#🔹 Task 2:
#Create a 3x4 NumPy array filled entirely with the number 7.
array2 = np.ones((3,4))
seven_array = np.array(array2 * 7)
print(seven_array)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [30]:
# Task 3: Generate 6 equally spaced values from -10 to 10
#🔹 Task 3:
#Generate an array of 6 equally spaced values starting from -10 to 10.
equal_array = np.linspace(-10,10,6)
print(equal_array)

[-10.  -6.  -2.   2.   6.  10.]


In [31]:
# Task 4: Create a 4x4 identity matrix
#🔹 Task 4:
#Create a 4x4 identity matrix using NumPy.
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
# Task 5: Generate 15 random integers between 50 and 100 inclusive
#🔹 Task 5:
#Generate an array of 15 random integers ranging from 50 to 100 (inclusive).
random_array = np.random.randint(50,101,15)
print(random_array)

[ 86  85  82  67  59  72  74  57  95  96  57  94  73  65 100]


In [2]:
# Creating a 3D NumPy array (2 blocks of 2x2 matrices)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Indexing specific elements from the 3D array
print(arr3[0, 1, 1])  # 4 (1st block, 2nd row, 2nd col)
print(arr3[1, 0, 0])  # 5 (2nd block, 1st row, 1st col)

4
5


A 3-dimensional array can be thought of as a collection of 2-dimensional arrays (matrices). Indexing and slicing work similarly to 2D arrays, but with an added dimension for the blocks.

Let's use the `arr3` array you created to demonstrate indexing and slicing.

In [ ]:
# Demonstrating slicing and indexing in a 3D array
# Original 3D array
print("Original 3D array:")
print(arr3)
print("-" * 20)

# Indexing: Accessing individual elements
print("Accessing elements:")
print(f"Element at arr3[0, 0, 0]: {arr3[0, 0, 0]}") # Access the element at the first block, first row, first column
print(f"Element at arr3[1, 1, 1]: {arr3[1, 1, 1]}") # Access the element at the second block, second row, second column
print("-" * 20)

# Slicing: Accessing subarrays
print("Slicing the array:")
print("First block:")
print(arr3[0, :, :]) # Slice the first block (all rows and columns within that block)
print("-" * 20)

print("Second row of all blocks:")
print(arr3[:, 1, :]) # Slice the second row across all blocks and all columns within that row
print("-" * 20)

print("First column of the first block:")
print(arr3[0, :, 0]) # Slice the first block, all rows, and the first column
print("-" * 20)

print("Sub-array from the first block, first row, and second column onwards:")
print(arr3[0, 0, 1:]) # Slice the first block, first row, and elements from the second column onwards
print("-" * 20)